<!-- Main Navigation-section : starts -->
<section id="navigation" class="navigation-section page-section secondary-bg">
	<!-- inner-section : starts -->
	<section class="inner-section">
		<!-- container : starts -->
		<section class="container">
			<div class="row">
				<article class="col-md-12 text-center">
					<div class="navigation-container">
						<div class="navigation-left">
							<ul>
								<li><a id="home-linker" class="nav-active scroll-link" href="index.html#home">home</a></li>
								<li><a id="services-linker" class="scroll-link" href="index.html#thecar">the car</a></li>
								<li><a id="works-linker" class="scroll-link" href="index.html#thespecs">the specs</a></li>
							</ul>
						</div>
						<div class="site-title text-center">EXILE AUTOMOTIVE</div>
						<div class="navigation-right">
							<ul>
								<li><a id="team-linker" class="scroll-link" href="exilehistory.html">the history</a></li>
								<li><a id="team-linker" class="scroll-link" href="index.html#theteam">the team</a></li>
								<li><a id="contact-linker" class="scroll-link" href="index.html#contact">contact us</a></li>
							</ul>
						</div>
					</div>	
				</article>
			</div>
		</section>
		<!-- container : ends -->
	</section>
	<!-- inner-section : ends -->
</section>
<!-- Main Navigation-section : ends -->