<!-- Sliding Navigation : starts -->
<nav class="menu" id="sm">
	<div class="sm-wrap">

		<i class="icon-remove menu-close"></i>
		<p class="site-name">EXILE</p>
		<a class="scroll-link"  href="index.html#home">Home</a>
		<a class="scroll-link"  href="index.html#thecar">the Car</a>
		<a class="scroll-link"  href="index.html#thespecs">the specs</a>
		<a class="scroll-link"  href="exilehistory.html">the hisotry</a>
		<a class="scroll-link"  href="index.html#theteam">the team</a>
		<a class="scroll-link"  href="index.html#contact">contact us</a>		
	</div>
	<!-- Navigation Trigger Button -->
	<div id="sm-trigger"></div>
</nav>
<!-- Sliding Navigation : ends -->

<!-- Master Wrap : starts -->
<section id="mastwrap" class="mast-wrap sliding">




<!-- masthead : starts -->
<header id="masthead" class="clearfix trans-header">
</header>
<!-- masthead : ends -->