<!-- quote-section : starts -->
<section id="quote" class="quote-section page-section add-top add-bottom parallax-slide-01">
	<!-- inner-section : starts -->
	<section class="inner-section">
		<!-- container : starts -->
		<section class="container">
			<div class="row">
				<article class="col-md-12 text-center">
					<div class="quote-container">

						<div id="quote-owl-demo" class="quote-owl">
						    <div class="item">
						    	<div class="row">
						    		<article class="col-md-8 col-md-offset-2">
						    			<h3>The car is like nothing I have ever driven before, and I've driven everything this side of £500k. Just astonishing</h3>
						    			<p>Justin Fielder, CEO</p>
						    		</article>
						    	</div>
						    </div>
						    <div class="item">
						    	<div class="row">
						    		<article class="col-md-8 col-md-offset-2">
						    			<h3>This really is the best car I have ever designed. Not only does it excel on track, finally I have cracked the road manners</h3>
						    			<p>Lee Noble</p>
						    		</article>
						    	</div>
						    </div>
						    <div class="item">
						    	<div class="row">
						    		<article class="col-md-8 col-md-offset-2">
						    			<h3>And it absolutly will not understeer, the is just tonnes and tonnes of grip.</h3>
						    			<p>Jeremey Clarkson - M12 reveiew</p>
						    		</article>
						    	</div>
						    </div>
						    <div class="item">
						    	<div class="row">
						    		<article class="col-md-8 col-md-offset-2">
						    			<h3>Lee Noble's track record is good as it gets, having penned a string of the world’s best-handling and fastest accelerating supercars</h3>
						    			<p>Jack Martin - GizMag</p>
						    		</article>
						    	</div>
						    </div>
						</div>
					
					</div>
				</article>
			</div>
		</section>
		<!-- container : ends -->
	</section>
	<!-- inner-section : ends -->
</section>
<!-- quote-section : ends -->